# Build Stage
FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY .env.production .env.production
RUN npm install
COPY . .

RUN npm run build

# Production Stage
FROM node:16-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
