services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - motosegura-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - web
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - motosegura-network

volumes:
  uploads:

networks:
  motosegura-network:
    driver: bridge 