services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - motosegura-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - web
    restart: always
    networks:
      - motosegura-network

networks:
  motosegura-network:
    driver: bridge
